# -*- coding: utf-8 -*-
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow

from service import FormatterService
from utils import Files, Dialogs


# Form implementation generated from reading ui file 'd:\Development\smalltools\Python\CompareData\ui\FileContent.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


class Ui_MainWindow(object):
    def __init__(self):
        self.window = QMainWindow()
        self.setupUi()

    def setupUi(self):
        self.window.setObjectName("MainWindow")
        self.window.resize(560, 257)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Development\\smalltools\\Python\\CompareData\\icon\\content.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.window.setWindowIcon(icon)
        self.verticalWidget = QtWidgets.QWidget(self.window)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.desc_text_browser = QtWidgets.QTextBrowser(self.verticalWidget)
        self.desc_text_browser.setObjectName("desc_text_browser")
        self.verticalLayout.addWidget(self.desc_text_browser)
        self.label_2 = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.upload_content_btn = QtWidgets.QPushButton(self.verticalWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.upload_content_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Development\\smalltools\\Python\\CompareData\\icon\\upload.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upload_content_btn.setIcon(icon1)
        self.upload_content_btn.setObjectName("upload_content_btn")
        self.verticalLayout.addWidget(self.upload_content_btn)
        self.exec_content_btn = QtWidgets.QPushButton(self.verticalWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exec_content_btn.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\Development\\smalltools\\Python\\CompareData\\icon\\execute.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exec_content_btn.setIcon(icon2)
        self.exec_content_btn.setObjectName("exec_content_btn")
        self.verticalLayout.addWidget(self.exec_content_btn)
        self.window.setCentralWidget(self.verticalWidget)

        self.retranslateUi(self.window)
        QtCore.QMetaObject.connectSlotsByName(self.window)

        self.upload_content_btn.clicked.connect(self.upload_content_btn_clicked)
        self.exec_content_btn.clicked.connect(self.exec_content_btn_clicked)

    def upload_content_btn_clicked(self):
        self.format_filepath = Files.openfile()

    def exec_content_btn_clicked(self):
        self.thread = FormatterService.FileContentFormatThread()
        self.thread.set_values(self.format_filepath)
        self.thread.success.connect(self.exec_btn_signal)
        self.thread.error.connect(lambda e: Dialogs.error(e))
        self.thread.start()

    def exec_btn_signal(self, output_path):
        self.output_path = output_path
        Dialogs.menu(f'制作完成。\n\n你可以打开文件，或打开文件夹，或关闭对话框。', self.mission_success_to_open_file,
                     self.mission_success_to_open_folder)

    def mission_success_to_open_file(self):
        os.startfile(self.output_path)

    def mission_success_to_open_folder(self):
        os.startfile(Files.get_folder(self.output_path))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "表格内容处理 - V1.0.2"))
        self.desc_text_browser.setHtml(_translate("MainWindow",
                                                  "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                  "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                  "p, li { white-space: pre-wrap; }\n"
                                                  "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                                  "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">工具说明</span></p>\n"
                                                  "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt; font-weight:600;\"><br /></p>\n"
                                                  "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">若</span><span style=\" font-size:10pt; font-weight:600;\">文件内容</span><span style=\" font-size:10pt;\">不符合要求，请执行下面 </span><span style=\" font-size:10pt; font-weight:600;\">文件内容转换</span><span style=\" font-size:10pt;\">，将文件内容转换为一行一行显示。</span></p>\n"
                                                  "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
                                                  "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
                                                  "<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; color:#ff0000;\">注意：在转换之前请删除原表格中的表头，只保留各列名。</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "文件内容转换"))
        self.upload_content_btn.setText(_translate("MainWindow", "上传要转换的文件内容的文件"))
        self.exec_content_btn.setText(_translate("MainWindow", "转换文件内容"))
