# -*- coding: utf-8 -*-
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QStatusBar

from service import FormatterService
from utils import Files, Dialogs


# Form implementation generated from reading ui file 'd:\Development\smalltools\Python\CompareData\ui\Formatter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


class Ui_MainWindow:
    def __init__(self):
        self.window = QtWidgets.QMainWindow()
        self.vertical_widget = QtWidgets.QWidget(self.window)
        self.vertical_layout = QtWidgets.QVBoxLayout(self.vertical_widget)

        self.label_1 = QtWidgets.QLabel(self.vertical_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_1.setFont(font)

        self.upload_btn = QtWidgets.QPushButton(self.vertical_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.upload_btn.setFont(font)

        self.label_2 = QtWidgets.QLabel(self.vertical_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_2.setFont(font)

        self.exec_btn = QtWidgets.QPushButton(self.vertical_widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.exec_btn.setFont(font)

        self.status_bar = QStatusBar(self.window)
        self.status_bar.setStyleSheet("color: red;")
        self.setup_ui()

    def setup_ui(self):
        self.window.setObjectName("MainWindow")
        self.window.resize(560, 112)

        self.vertical_layout.addWidget(self.label_1)
        self.vertical_layout.addWidget(self.upload_btn)
        self.vertical_layout.addWidget(self.label_2)
        self.vertical_layout.addWidget(self.exec_btn)

        self.window.setCentralWidget(self.vertical_widget)

        self.window.setStatusBar(self.status_bar)

        self.retranslate_ui()

        self.upload_btn.clicked.connect(self.upload_btn_clicked)
        self.exec_btn.clicked.connect(self.exec_btn_clicked)

    def upload_btn_clicked(self):
        self.filepath = Files.openfile()
        self.status_bar.showMessage("成功上传需要重组的表格。")

    def exec_btn_clicked(self):
        self.thread = FormatterService.FormatThread()
        self.thread.set_values(self.filepath)
        self.thread.error.connect(lambda e: Dialogs.error(e))
        self.thread.success.connect(
            lambda e: Dialogs.menu(e, self.mission_success_to_open_file, self.mission_success_to_open_folder))
        self.thread.start()

    def mission_success_to_open_file(self):
        output_path = os.path.join(Files.get_folder(self.filepath), f"{Files.get_filename(self.filepath)}_格式化.xlsx")
        os.startfile(output_path)
        self.status_bar.showMessage("已经打开指定文件，可关闭该窗口。")

    def mission_success_to_open_folder(self):
        os.startfile(Files.get_folder(self.filepath))
        self.status_bar.showMessage("已经打开指定文件夹，可关闭该窗口。")

    def retranslate_ui(self):
        _translate = QtCore.QCoreApplication.translate
        self.window.setWindowTitle(_translate("MainWindow", "重组表格工具 V1.0.0 From 郑人滏"))
        self.label_1.setText(_translate("MainWindow", "上传"))
        self.upload_btn.setText(_translate("MainWindow", "上传文件"))
        self.label_2.setText(_translate("MainWindow", "输出"))
        self.exec_btn.setText(_translate("MainWindow", "执行任务"))
