# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Development\smalltools\Python\CompareData\ui\InfoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_MainWindow(object):
    def __init__(self):
        self.dialog = QMainWindow()
        self.setupUi()

    def setupUi(self):
        self.dialog.setObjectName("MainWindow")
        self.dialog.resize(477, 244)
        self.centralwidget = QtWidgets.QWidget(self.dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayoutWidget.setProperty("geometry", QtCore.QRect(120, 110, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayoutWidget.addWidget(self.textBrowser)
        self.dialog.setCentralWidget(self.centralwidget)

        self.retranslateUi(self.dialog)
        QtCore.QMetaObject.connectSlotsByName(self.dialog)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Info", "Info"))
        self.textBrowser.setHtml(_translate("Info",
                                            "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">关于该程序</span></p>\n"
                                            "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">该程序全名吐鲁番市药品耗材差额对比程序，即核对医疗机构HIS和招财平台入库汇总对比表生成器。</span></p>\n"
                                            "<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">1. 程序在线下载地址：</span>https://gitee.com/Himmelbleu/smalltools/releases<br /><span style=\" font-size:10pt;\">2. 程序在线文档：https://www.kdocs.cn/l/cdeeX4uvJAue</span></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
                                            "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;\"><br /></p>\n"
                                            "<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">若有问题，微信联系：Himmelbleu、Sangqingdan、_15523484368</p>\n"
                                            "<p align=\"right\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">版本: 2.4.2</p>\n"
                                            "<p align=\"right\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">作者: Himmelbleu</p></body></html>"))
