# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Projects\py_tools\Copyer\copyer_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QMessageBox

import copy_signal_file
import copyer_threads


class Ui_Copyer(object):
    def setupUi(self, Copyer):
        Copyer.setObjectName("Copyer")
        Copyer.resize(777, 500)
        self.main_widget = QtWidgets.QWidget(Copyer)
        self.main_widget.setObjectName("main_widget")
        self.decrypt_signal_file = QtWidgets.QRadioButton(self.main_widget)
        self.decrypt_signal_file.setGeometry(QtCore.QRect(320, 10, 115, 19))
        self.decrypt_signal_file.setChecked(False)
        self.decrypt_signal_file.setObjectName("decrypt_signal_file")
        self.decrypt_multi_files = QtWidgets.QRadioButton(self.main_widget)
        self.decrypt_multi_files.setGeometry(QtCore.QRect(20, 10, 211, 19))
        self.decrypt_multi_files.setChecked(True)
        self.decrypt_multi_files.setObjectName("decrypt_multi_files")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_widget)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 50, 741, 391))
        self.stackedWidget.setObjectName("stackedWidget")
        self.signal_file_page = QtWidgets.QWidget()
        self.signal_file_page.setObjectName("signal_file_page")
        self.signal_file_selector_btn = QtWidgets.QPushButton(self.signal_file_page)
        self.signal_file_selector_btn.setGeometry(QtCore.QRect(0, 0, 121, 28))
        self.signal_file_selector_btn.setObjectName("signal_file_selector_btn")
        self.signal_file_decrypt_dest_dir_selector_btn = QtWidgets.QPushButton(self.signal_file_page)
        self.signal_file_decrypt_dest_dir_selector_btn.setGeometry(QtCore.QRect(0, 50, 121, 28))
        self.signal_file_decrypt_dest_dir_selector_btn.setObjectName("signal_file_decrypt_dest_dir_selector_btn")
        self.signal_file_textarea = QtWidgets.QTextBrowser(self.signal_file_page)
        self.signal_file_textarea.setGeometry(QtCore.QRect(0, 100, 721, 192))
        self.signal_file_textarea.setObjectName("signal_file_textarea")
        self.signal_file_label = QtWidgets.QLabel(self.signal_file_page)
        self.signal_file_label.setGeometry(QtCore.QRect(140, 0, 581, 28))
        self.signal_file_label.setText("")
        self.signal_file_label.setObjectName("signal_file_label")
        self.signal_file_dest_dir_label = QtWidgets.QLabel(self.signal_file_page)
        self.signal_file_dest_dir_label.setGeometry(QtCore.QRect(140, 50, 581, 28))
        self.signal_file_dest_dir_label.setText("")
        self.signal_file_dest_dir_label.setObjectName("signal_file_dest_dir_label")
        self.start_decrypt_signal_file = QtWidgets.QPushButton(self.signal_file_page)
        self.start_decrypt_signal_file.setGeometry(QtCore.QRect(630, 350, 90, 40))
        self.start_decrypt_signal_file.setObjectName("start_decrypt_signal_file")
        self.stackedWidget.addWidget(self.signal_file_page)
        self.multi_file_page = QtWidgets.QWidget()
        self.multi_file_page.setObjectName("multi_file_page")
        self.multi_file_dest_dir_label = QtWidgets.QLabel(self.multi_file_page)
        self.multi_file_dest_dir_label.setGeometry(QtCore.QRect(140, 50, 581, 28))
        self.multi_file_dest_dir_label.setText("")
        self.multi_file_dest_dir_label.setObjectName("multi_file_dest_dir_label")
        self.multi_file_dir_label = QtWidgets.QLabel(self.multi_file_page)
        self.multi_file_dir_label.setGeometry(QtCore.QRect(140, 0, 581, 28))
        self.multi_file_dir_label.setText("")
        self.multi_file_dir_label.setObjectName("multi_file_dir_label")
        self.multi_file_textarea = QtWidgets.QTextBrowser(self.multi_file_page)
        self.multi_file_textarea.setGeometry(QtCore.QRect(0, 100, 721, 192))
        self.multi_file_textarea.setObjectName("multi_file_textarea")
        self.start_decrypt_multi_file = QtWidgets.QPushButton(self.multi_file_page)
        self.start_decrypt_multi_file.setGeometry(QtCore.QRect(630, 350, 90, 40))
        self.start_decrypt_multi_file.setObjectName("start_decrypt_multi_file")
        self.multi_file_dir_selector_btn = QtWidgets.QPushButton(self.multi_file_page)
        self.multi_file_dir_selector_btn.setGeometry(QtCore.QRect(0, 0, 121, 28))
        self.multi_file_dir_selector_btn.setObjectName("multi_file_dir_selector_btn")
        self.multi_file_decrypt_dest_dir_selector_btn = QtWidgets.QPushButton(self.multi_file_page)
        self.multi_file_decrypt_dest_dir_selector_btn.setGeometry(QtCore.QRect(0, 50, 121, 28))
        self.multi_file_decrypt_dest_dir_selector_btn.setObjectName("multi_file_decrypt_dest_dir_selector_btn")
        self.multi_file_num_label = QtWidgets.QLabel(self.multi_file_page)
        self.multi_file_num_label.setGeometry(QtCore.QRect(0, 310, 70, 23))
        self.multi_file_num_label.setObjectName("multi_file_num_label")
        self.multi_file_decrypt_progress = QtWidgets.QProgressBar(self.multi_file_page)
        self.multi_file_decrypt_progress.setGeometry(QtCore.QRect(180, 310, 451, 23))
        self.multi_file_decrypt_progress.setProperty("value", 0)
        self.multi_file_decrypt_progress.setObjectName("multi_file_decrypt_progress")
        self.multi_file_num = QtWidgets.QLabel(self.multi_file_page)
        self.multi_file_num.setGeometry(QtCore.QRect(80, 310, 72, 23))
        self.multi_file_num.setObjectName("multi_file_num")
        self.stackedWidget.addWidget(self.multi_file_page)
        Copyer.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(Copyer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 777, 26))
        self.menubar.setObjectName("menubar")
        Copyer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Copyer)
        self.statusbar.setObjectName("statusbar")
        Copyer.setStatusBar(self.statusbar)

        self.retranslateUi(Copyer)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Copyer)

        self.decrypt_signal_file.toggled.connect(self.on_radio_button_toggled)
        self.decrypt_multi_files.toggled.connect(self.on_radio_button_toggled)

        self.signal_file_selector_btn.clicked.connect(self.on_signal_file_selector)
        self.signal_file_decrypt_dest_dir_selector_btn.clicked.connect(self.on_signal_file_decrypt_des_dir_selector)
        self.start_decrypt_signal_file.clicked.connect(self.on_start_decrypt_signal_file)

        self.multi_file_dir_selector_btn.clicked.connect(self.on_multi_file_dir_selector_btn)
        self.multi_file_decrypt_dest_dir_selector_btn.clicked.connect(self.on_multi_file_decrypt_des_dir_selector)
        self.start_decrypt_multi_file.clicked.connect(self.on_start_decrypt_multi_file)

    def on_radio_button_toggled(self):
        if self.decrypt_signal_file.isChecked():
            self.stackedWidget.setCurrentIndex(0)
        elif self.decrypt_multi_files.isChecked():
            self.stackedWidget.setCurrentIndex(1)

    def on_signal_file_selector(self):
        self.open_file_dialog_thread = copyer_threads.OpenFileDialogThread()
        self.open_file_dialog_thread.updator.connect(lambda x: {
            self.signal_file_label.setText(x)
        })
        self.open_file_dialog_thread.file_type = "1"
        self.open_file_dialog_thread.start()

    def on_signal_file_decrypt_des_dir_selector(self):
        self.open_file_dialog_thread = copyer_threads.OpenFileDialogThread()
        self.open_file_dialog_thread.updator.connect(lambda x: {
            self.signal_file_dest_dir_label.setText(x)
        })
        self.open_file_dialog_thread.file_type = "2"
        self.open_file_dialog_thread.start()

    def on_start_decrypt_signal_file(self):
        source_folder = self.signal_file_label.text()
        des_folder = self.signal_file_dest_dir_label.text()
        if not source_folder or not des_folder:
            QMessageBox(QMessageBox.Warning, '提示', '请选择文件和文件解压位置！').exec_()
        else:
            copy_signal_file.decrypt_signal_file(source_folder, des_folder, self.after_decrypt_signal_file)

    def after_decrypt_signal_file(self, data):
        self.signal_file_textarea.append(
            f"文件 '{data['source_file']}' 已复制到目标目录 '{data['des_folder']}' 中......\n")

    def on_multi_file_dir_selector_btn(self):
        self.open_file_dialog_thread = copyer_threads.OpenFileDialogThread()
        self.open_file_dialog_thread.updator.connect(lambda x: {
            self.multi_file_dir_label.setText(x)
        })
        self.open_file_dialog_thread.file_type = "2"
        self.open_file_dialog_thread.start()

    def on_multi_file_decrypt_des_dir_selector(self):
        self.open_file_dialog_thread = copyer_threads.OpenFileDialogThread()
        self.open_file_dialog_thread.updator.connect(lambda x: {
            self.multi_file_dest_dir_label.setText(x)
        })
        self.open_file_dialog_thread.file_type = "2"
        self.open_file_dialog_thread.start()

    def on_start_decrypt_multi_file(self):
        source_folder = self.multi_file_dir_label.text()
        des_folder = self.multi_file_dest_dir_label.text()
        if not source_folder or not des_folder:
            QMessageBox(QMessageBox.Warning, '提示', '请选择文件夹路径和文件解压位置！').exec_()
        else:
            self.decrypt_multi_file_thread = copyer_threads.DecryptMultiFileThread(source_folder, des_folder)
            self.decrypt_multi_file_thread.updator.connect(self.after_decrypt_multi_file_thread)
            self.decrypt_multi_file_thread.start()

    def after_decrypt_multi_file_thread(self, data):
        self.multi_file_decrypt_progress.setValue(data['progress'])
        self.multi_file_num.setText(data['file_count'])
        self.multi_file_textarea.append(data['text'])
        if data['e']:
            QMessageBox(QMessageBox.Warning, '错误', str(data['e'])).exec_()

    def retranslateUi(self, Copyer):
        _translate = QtCore.QCoreApplication.translate
        Copyer.setWindowTitle(_translate("Copyer", "文件解密器"))
        self.decrypt_signal_file.setText(_translate("Copyer", "解密单个文件"))
        self.decrypt_multi_files.setText(_translate("Copyer", "解密文件夹下所有文件"))
        self.signal_file_selector_btn.setText(_translate("Copyer", "选择文件"))
        self.signal_file_decrypt_dest_dir_selector_btn.setText(_translate("Copyer", "选择解密位置"))
        self.start_decrypt_signal_file.setText(_translate("Copyer", "开始解密"))
        self.start_decrypt_multi_file.setText(_translate("Copyer", "开始解密"))
        self.multi_file_dir_selector_btn.setText(_translate("Copyer", "选择文件夹"))
        self.multi_file_decrypt_dest_dir_selector_btn.setText(_translate("Copyer", "选择解密位置"))
        self.multi_file_num_label.setText(_translate("Copyer", "文件个数"))
        self.multi_file_num.setText(_translate("Copyer", "0"))
